apiVersion: v1
kind: Namespace
metadata:
  name: giraldo_pablo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: giraldo_pablo
  name: giraldo-pablo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tu-app
  template:
    metadata:
      labels:
        app: tu-app
    spec:
      containers:
      - name: tu-app
        image: fercdew/scale-flask:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: secret-volume
          mountPath: /etc/secrets
      volumes:
      - name: config-volume
        configMap:
          name: giraldo-pablo-configmap
      - name: secret-volume
        secret:
          secretName: giraldo-pablo-secret

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: giraldo_pablo
  name: giraldo-pablo-configmap
data:
  archivo.log: "Pablo Giraldo presente"

---

apiVersion: v1
kind: Secret
metadata:
  namespace: giraldo_pablo
  name: giraldo-pablo-secret
stringData:
  apellido_paterno: "Giraldo"
  apellido_materno: "Moran"

---

apiVersion: v1
kind: Service
metadata:
  namespace: giraldo_pablo
  name: giraldo-pablo-service
spec:
  selector:
    app: tu-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: giraldo_pablo
  name: giraldo-pablo-cronjob
spec:
  schedule: "*/4 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            command: ["curl", "-o", "/dev/null", "http://giraldo-pablo-service.default.svc.cluster.local"]
          restartPolicy: OnFailure
